# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd6e7b0e18f324e517bfbc632463e6efae135f4fd2b7f8434fda764f46fcc268581a99a8659cf00d6ecc23e79cbb1544f0d3f75a41d8935f4044f56921a2d6df

test:
  secret_key_base: 151ec2507df6e57835da0ea33e947c3cd798ec6145f866c6653839f22ba9cd94a2985948b946f9b1d339ccd996ae07a01a8928cb3a6e8d9608f202e0efa8f7d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
